import { Card } from "../types";
import {
  faCarrot,
  faPizzaSlice,
  faEgg,
  faLemon,
  faAppleWhole,
  faIceCream,
  faBurger,
  faShrimp,
  faSnowflake,
  faVolcano,
  faRainbow,
  faCloud,
  faTree,
  faLeaf,
  faFeatherPointed,
  faFire,
  faSpider,
  faFrog,
  faWorm,
  faMosquito,
  faCat,
  faHorse,
  faHippo,
  faFishFins,
  faCheese,
  faDrumstickBite,
  faJar,
  faWheatAwn,
  faMugSaucer,
  faBowlFood,
  faPepperHot,
  faCloudBolt,
  faTornado,
  faSunPlantWilt,
  faCloudShowersHeavy,
  faSun,
  faMoon,
  faIcicles,
  faDove,
  faCow,
  faOtter,
  faLocust,
  faCrow,
  faDog,
  faKiwiBird,
} from "@fortawesome/free-solid-svg-icons";

export const foodCards: Card[] = [
  { id: 1, icon: faCarrot, style: { color: "#dd732c" } },
  { id: 2, icon: faCarrot, style: { color: "#dd732c" } },
  { id: 3, icon: faPizzaSlice, style: { color: "#321b0c" } },
  { id: 4, icon: faPizzaSlice, style: { color: "#321b0c" } },
  { id: 5, icon: faEgg, style: { color: "#f6f4f3" } },
  { id: 6, icon: faEgg, style: { color: "#f6f4f3" } },
  { id: 7, icon: faLemon, style: { color: "#edea11" } },
  { id: 8, icon: faLemon, style: { color: "#edea11" } },
  { id: 9, icon: faAppleWhole, style: { color: "#cc1313" } },
  { id: 10, icon: faAppleWhole, style: { color: "#cc1313" } },
  { id: 11, icon: faIceCream, style: { color: "#135dcc" } },
  { id: 12, icon: faIceCream, style: { color: "#135dcc" } },
  { id: 13, icon: faBurger, style: { color: "#5e2f2f" } },
  { id: 14, icon: faBurger, style: { color: "#5e2f2f" } },
  { id: 15, icon: faShrimp, style: { color: "#e9609e" } },
  { id: 16, icon: faShrimp, style: { color: "#e9609e" } },
  { id: 17, icon: faCheese, style: { color: "#ddda41" } },
  { id: 18, icon: faCheese, style: { color: "#ddda41" } },
  { id: 19, icon: faDrumstickBite, style: { color: "#7a4f09" } },
  { id: 20, icon: faDrumstickBite, style: { color: "#7a4f09" } },
  { id: 21, icon: faJar, style: { color: "#429ccc" } },
  { id: 22, icon: faJar, style: { color: "#429ccc" } },
  { id: 23, icon: faWheatAwn, style: { color: "#b7ad16" } },
  { id: 24, icon: faWheatAwn, style: { color: "#b7ad16" } },
  { id: 25, icon: faMugSaucer, style: { color: "#969188" } },
  { id: 26, icon: faMugSaucer, style: { color: "#969188" } },
  { id: 27, icon: faBowlFood, style: { color: "#428533" } },
  { id: 28, icon: faBowlFood, style: { color: "#428533" } },
  { id: 29, icon: faPepperHot, style: { color: "#a3231a" } },
  { id: 30, icon: faPepperHot, style: { color: "#a3231a" } },
];

export const natureCards: Card[] = [
  { id: 1, icon: faSnowflake, style: { color: "#4a87d8" } },
  { id: 2, icon: faSnowflake, style: { color: "#4a87d8" } },
  { id: 3, icon: faVolcano, style: { color: "#321b0c" } },
  { id: 4, icon: faVolcano, style: { color: "#321b0c" } },
  { id: 5, icon: faRainbow, style: { color: "#e347c9f5" } },
  { id: 6, icon: faRainbow, style: { color: "#e347c9f5" } },
  { id: 7, icon: faCloud, style: { color: "#2c26d9" } },
  { id: 8, icon: faCloud, style: { color: "#2c26d9" } },
  { id: 9, icon: faTree, style: { color: "#0b9640" } },
  { id: 10, icon: faTree, style: { color: "#0b9640" } },
  { id: 11, icon: faLeaf, style: { color: "#66c743" } },
  { id: 12, icon: faLeaf, style: { color: "#66c743" } },
  { id: 13, icon: faFeatherPointed, style: { color: "#b7abab" } },
  { id: 14, icon: faFeatherPointed, style: { color: "#b7abab" } },
  { id: 15, icon: faFire, style: { color: "#d63b10" } },
  { id: 16, icon: faFire, style: { color: "#d63b10" } },
  { id: 17, icon: faCloudBolt, style: { color: "#676563" } },
  { id: 18, icon: faCloudBolt, style: { color: "#676563" } },
  { id: 19, icon: faTornado, style: { color: "#906e38" } },
  { id: 20, icon: faTornado, style: { color: "#906e38" } },
  { id: 21, icon: faSunPlantWilt, style: { color: "#2d7522" } },
  { id: 22, icon: faSunPlantWilt, style: { color: "#2d7522" } },
  { id: 23, icon: faCloudShowersHeavy, style: { color: "#a0988a" } },
  { id: 24, icon: faCloudShowersHeavy, style: { color: "#a0988a" } },
  { id: 25, icon: faSun, style: { color: "#e7dc15" } },
  { id: 26, icon: faSun, style: { color: "#e7dc15" } },
  { id: 27, icon: faMoon, style: { color: "#dada12" } },
  { id: 28, icon: faMoon, style: { color: "#dada12" } },
  { id: 29, icon: faIcicles, style: { color: "#02b5cd" } },
  { id: 30, icon: faIcicles, style: { color: "#02b5cd" } },
];

export const animalCards: Card[] = [
  { id: 1, icon: faSpider, style: { color: "#12100f" } },
  { id: 2, icon: faSpider, style: { color: "#12100f" } },
  { id: 3, icon: faFrog, style: { color: "#1a6216" } },
  { id: 4, icon: faFrog, style: { color: "#1a6216" } },
  { id: 5, icon: faWorm, style: { color: "#d672bb" } },
  { id: 6, icon: faWorm, style: { color: "#d672bb" } },
  { id: 7, icon: faMosquito, style: { color: "#b77320" } },
  { id: 8, icon: faMosquito, style: { color: "#b77320" } },
  { id: 9, icon: faCat, style: { color: "#b3a89d" } },
  { id: 10, icon: faCat, style: { color: "#b3a89d" } },
  { id: 11, icon: faHorse, style: { color: "#583c19" } },
  { id: 12, icon: faHorse, style: { color: "#583c19" } },
  { id: 13, icon: faHippo, style: { color: "#636b71" } },
  { id: 14, icon: faHippo, style: { color: "#636b71" } },
  { id: 15, icon: faFishFins, style: { color: "#6f85df" } },
  { id: 16, icon: faFishFins, style: { color: "#6f85df" } },
  { id: 17, icon: faDove, style: { color: "#a29e9e" } },
  { id: 18, icon: faDove, style: { color: "#a29e9e" } },
  { id: 19, icon: faCow, style: { color: "#100c05" } },
  { id: 20, icon: faCow, style: { color: "#100c05" } },
  { id: 21, icon: faOtter, style: { color: "#906e38" } },
  { id: 22, icon: faOtter, style: { color: "#906e38" } },
  { id: 23, icon: faLocust, style: { color: "#518c3d" } },
  { id: 24, icon: faLocust, style: { color: "#518c3d" } },
  { id: 25, icon: faCrow, style: { color: "#702e99" } },
  { id: 26, icon: faCrow, style: { color: "#702e99" } },
  { id: 27, icon: faDog, style: { color: "#906e38" } },
  { id: 28, icon: faDog, style: { color: "#906e38" } },
  { id: 29, icon: faKiwiBird, style: { color: "#7b5a24" } },
  { id: 30, icon: faKiwiBird, style: { color: "#7b5a24" } },
];
