import { Card } from "../types";
import {
  faCarrot,
  faPizzaSlice,
  faEgg,
  faLemon,
  faAppleWhole,
  faIceCream,
  faBurger,
  faShrimp,
  faSnowflake,
  faVolcano,
  faRainbow,
  faCloud,
  faTree,
  faLeaf,
  faFeatherPointed,
  faFire,
  faSpider,
  faFrog,
  faWorm,
  faMosquito,
  faCat,
  faHorse,
  faHippo,
  faFishFins,
} from "@fortawesome/free-solid-svg-icons";

export const foodCards: Card[] = [
  { id: 1, icon: faCarrot, style: { color: "#dd732c" } },
  { id: 2, icon: faCarrot, style: { color: "#dd732c" } },
  { id: 3, icon: faPizzaSlice, style: { color: "#321b0c" } },
  { id: 4, icon: faPizzaSlice, style: { color: "#321b0c" } },
  { id: 5, icon: faEgg, style: { color: "#f6f4f3" } },
  { id: 6, icon: faEgg, style: { color: "#f6f4f3" } },
  { id: 7, icon: faLemon, style: { color: "#edea11" } },
  { id: 8, icon: faLemon, style: { color: "#edea11" } },
  { id: 9, icon: faAppleWhole, style: { color: "#cc1313" } },
  { id: 10, icon: faAppleWhole, style: { color: "#cc1313" } },
  { id: 11, icon: faIceCream, style: { color: "#135dcc" } },
  { id: 12, icon: faIceCream, style: { color: "#135dcc" } },
  { id: 13, icon: faBurger, style: { color: "#5e2f2f" } },
  { id: 14, icon: faBurger, style: { color: "#5e2f2f" } },
  { id: 15, icon: faShrimp, style: { color: "#e9609e" } },
  { id: 16, icon: faShrimp, style: { color: "#e9609e" } },
];

export const natureCards: Card[] = [
  { id: 1, icon: faSnowflake, style: { color: "#4a87d8" } },
  { id: 2, icon: faSnowflake, style: { color: "#4a87d8" } },
  { id: 3, icon: faVolcano, style: { color: "#321b0c" } },
  { id: 4, icon: faVolcano, style: { color: "#321b0c" } },
  { id: 5, icon: faRainbow, style: { color: "#e347c9f5" } },
  { id: 6, icon: faRainbow, style: { color: "#e347c9f5" } },
  { id: 7, icon: faCloud, style: { color: "#2c26d9" } },
  { id: 8, icon: faCloud, style: { color: "#2c26d9" } },
  { id: 9, icon: faTree, style: { color: "#0b9640" } },
  { id: 10, icon: faTree, style: { color: "#0b9640" } },
  { id: 11, icon: faLeaf, style: { color: "#66c743" } },
  { id: 12, icon: faLeaf, style: { color: "#66c743" } },
  { id: 13, icon: faFeatherPointed, style: { color: "#6d6b6b" } },
  { id: 14, icon: faFeatherPointed, style: { color: "#6d6b6b" } },
  { id: 15, icon: faFire, style: { color: "#d63b10" } },
  { id: 16, icon: faFire, style: { color: "#d63b10" } },
];

export const animalCards: Card[] = [
  { id: 1, icon: faSpider, style: { color: "#12100f" } },
  { id: 2, icon: faSpider, style: { color: "#12100f" } },
  { id: 3, icon: faFrog, style: { color: "#1a6216" } },
  { id: 4, icon: faFrog, style: { color: "#1a6216" } },
  { id: 5, icon: faWorm, style: { color: "#d672bb" } },
  { id: 6, icon: faWorm, style: { color: "#d672bb" } },
  { id: 7, icon: faMosquito, style: { color: "#b77320" } },
  { id: 8, icon: faMosquito, style: { color: "#b77320" } },
  { id: 9, icon: faCat, style: { color: "#f4eee8" } },
  { id: 10, icon: faCat, style: { color: "#f4eee8" } },
  { id: 11, icon: faHorse, style: { color: "#583c19" } },
  { id: 12, icon: faHorse, style: { color: "#583c19" } },
  { id: 13, icon: faHippo, style: { color: "#636b71" } },
  { id: 14, icon: faHippo, style: { color: "#636b71" } },
  { id: 15, icon: faFishFins, style: { color: "#6f85df" } },
  { id: 16, icon: faFishFins, style: { color: "#6f85df" } },
];
